### ISSUE TITLE
Consider replacing futures_codec with tokio_util

### ISSUE THREAD

**Issue by rukai** [vv9k/docker-api-rs#23]
futures_codec is unmaintained and pulls in outdated versions of `bytes` and `pin-project` https://deps.rs/crate/futures_codec/0.4.1

I propose that we swap futures_codec with tokio_util (I'm not sure of the exact history here but it seems one was copied into the other at some point because they have the same API)
futures_codec is async runtime agnostic, so if we planned to make docker-api async runtime agnostic as well then using tokio_util would be a misstep. But currently docker-api does use tokio making docker-api tokio specific.

I would be happy to provide a PR to perform this change (here and in container-api), but wanted to check in first to see if this was the right direction.

**Comment by vv9k** [comment]
In general I agree that it will be beneficial to replace `futures_codec` because it's pulling older dependencies so I'm all for it. I'd like to keep the possibility to make docker-api runtime agnostic one day so maybe there is another solution to use an active fork of `futures_codec` -> [`asynchronous codec`](https://github.com/mxinden/asynchronous-codec) that provides the same functionality but has updated dependencies and so on.

If you'd like to take this on then please do.

**Comment by rukai** [comment]
asynchronous_codec sounds like the best way forward to.
It doesnt seem particularly maintained either, unlike tokio_util which continues to receive updates, but at the very least asynchrous_codec has bytes and pin-project on their 1.0 releases which I dont expect to need updating again any time soon.

I'll go ahead and make PRs for both projects
